using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace PLN
{
    internal class dados
    {
        public string stopwords = @"a
                                    e
                                    o
                                    vezes
                                    estar
                                    tao
                                    daqueles
                                    dever
                                    enquanto
                                    assim
                                    pequenas
                                    pequenos
                                    de
                                    a
                                    o
                                    que
                                    e
                                    do
                                    da
                                    em
                                    um
                                    para
                                    e
                                    com
                                    nao
                                    uma
                                    os
                                    no
                                    se
                                    na
                                    por
                                    mais
                                    as
                                    dos
                                    como
                                    mas
                                    foi
                                    ao
                                    ele
                                    das
                                    tem
                                    a
                                    seu
                                    sua
                                    ou
                                    ser
                                    quando
                                    muito
                                    ha
                                    nos
                                    ja
                                    esta
                                    eu
                                    tambem
                                    so
                                    pelo
                                    pela
                                    ate
                                    isso
                                    ela
                                    entre
                                    era
                                    depois
                                    sem
                                    mesmo
                                    aos
                                    ter
                                    seus
                                    quem
                                    nas
                                    me
                                    esse
                                    eles
                                    estao
                                    voce
                                    tinha
                                    foram
                                    essa
                                    num
                                    nem
                                    suas
                                    meu
                                    as
                                    minha
                                    tem
                                    numa
                                    pelos
                                    elas
                                    havia
                                    seja
                                    qual
                                    sera
                                    nos
                                    tenho
                                    lhe
                                    deles
                                    essas
                                    esses
                                    pelas
                                    este
                                    fosse
                                    dele
                                    tu
                                    te
                                    voces
                                    vos
                                    lhes
                                    meus
                                    minhas
                                    teu
                                    tua
                                    teus
                                    tuas
                                    nosso
                                    nossa
                                    nossos
                                    nossas
                                    dela
                                    delas
                                    esta
                                    estes
                                    estas
                                    aquele
                                    aquela
                                    aqueles
                                    aquelas
                                    isto
                                    aquilo
                                    estou
                                    esta
                                    estamos
                                    estao
                                    estive
                                    esteve
                                    estivemos
                                    estiveram
                                    estava
                                    estavamos
                                    estavam
                                    estivera
                                    estiveramos
                                    esteja
                                    estejamos
                                    estejam
                                    estivesse
                                    estivessemos
                                    estivessem
                                    estiver
                                    estivermos
                                    estiverem
                                    hei
                                    ha
                                    havemos
                                    hao
                                    houve
                                    houvemos
                                    houveram
                                    houvera
                                    houveramos
                                    haja
                                    hajamos
                                    hajam
                                    houvesse
                                    houvessemos
                                    houvessem
                                    houver
                                    houvermos
                                    houverem
                                    houverei
                                    houvera
                                    houveremos
                                    houverao
                                    houveria
                                    houveriamos
                                    houveriam
                                    sou
                                    somos
                                    sao
                                    era
                                    eramos
                                    eram
                                    fui
                                    foi
                                    fomos
                                    foram
                                    fora
                                    foramos
                                    seja
                                    sejamos
                                    sejam
                                    fosse
                                    fossemos
                                    fossem
                                    for
                                    formos
                                    forem
                                    serei
                                    sera
                                    seremos
                                    serao
                                    seria
                                    seriamos
                                    seriam
                                    tenho
                                    tem
                                    temos
                                    tem
                                    tinha
                                    tinhamos
                                    tinham
                                    tive
                                    teve
                                    tivemos
                                    tiveram
                                    tivera
                                    tiveramos
                                    tenha
                                    tenhamos
                                    tenham
                                    tivesse
                                    tivessemos
                                    tivessem
                                    tiver
                                    tivermos
                                    tiverem
                                    terei
                                    tera
                                    teremos
                                    terao
                                    teria
                                    teriamos
                                    teriam
                                    poder
                                    primeiro
                                    ter
                                    tem
                                    proprias
                                    proprios
                                    tampouco
                                    aqueles
                                    aquelas
                                    agir
                                    ir
                                    el
                                    era
                                    algumas
                                    quem
                                    atraves
                                    contudo
                                    daquele
                                    fazer
                                    grandes
                                    ninguem
                                    pequena
                                    pequeno
                                    perante
                                    proprio
                                    quantos
                                    todavia
                                    quando
                                    tambem
                                    depois
                                    minhas
                                    minha
                                    nossos
                                    nossas
                                    aquele
                                    aquela
                                    aquilo
                                    alguem
                                    alguma
                                    algun
                                    algum
                                    coisas
                                    dessas
                                    desses
                                    destas
                                    destes
                                    feitas
                                    feitos
                                    grande
                                    mesmas
                                    mesmos
                                    muitas
                                    muitos
                                    nenhum
                                    nessas
                                    nestas
                                    outras
                                    outros
                                    porque
                                    poucas
                                    poucos
                                    seguir
                                    quanto
                                    sempre
                                    talvez
                                    ultima
                                    ultimo
                                    muito
                                    entre
                                    mesmo
                                    pelos
                                    deles
                                    essas
                                    esses
                                    pelas
                                    voces
                                    nosso
                                    nossa
                                    delas
                                    estes
                                    estas
                                    agora
                                    ainda
                                    antes
                                    coisa
                                    mas
                                    as
                                    dessa
                                    desta
                                    disse
                                    disso
                                    disto
                                    dizer
                                    feita
                                    feito
                                    mesma
                                    muita
                                    nessa
                                    nesta
                                    nunca
                                    outra
                                    outro
                                    pouca
                                    pouco
                                    sobre
                                    todas
                                    todos
                                    para
                                    alem
                                    mais
                                    como
                                    esta
                                    pelo
                                    pela
                                    isso
                                    seu
                                    quer
                                    eles
                                    voce
                                    essa
                                    suas
                                    onde
                                    tais
                                    numa
                                    elas
                                    seja
                                    qual
                                    dele
                                    lhes
                                    meus
                                    teus
                                    tuas
                                    dela
                                    isto
                                    haja
                                    aqui
                                    fora
                                    ante
                                    apos
                                    cada
                                    pois
                                    toda
                                    todo
                                    tudo
                                    umas
                                    lhos
                                    lhas
                                    que
                                    com
                                    uma
                                    por
                                    dos
                                    foi
                                    ele
                                    das
                                    sua
                                    nos
                                    ate
                                    ela
                                    aos
                                    nas
                                    num
                                    nem
                                    em
                                    meu
                                    tal
                                    lhe
                                    vos
                                    tua
                                    hei
                                    hao
                                    sou
                                    ou
                                    sao
                                    ali
                                    fui
                                    for
                                    pra
                                    diz
                                    per
                                    sob
                                    uns
                                    vez
                                    mos
                                    tos
                                    lho
                                    lha
                                    los
                                    las
                                    dai
                                    de
                                    do
                                    da
                                    um
                                    os
                                    no
                                    se
                                    na
                                    as
                                    ao
                                    ha
                                    ja
                                    so
                                    me
                                    tu
                                    te
                                    la
                                    ca
                                    lo
                                    si
                                    ti
                                    mo
                                    ma
                                    to
                                    ta
                                    a
                                    b
                                    c
                                    d
                                    e
                                    f
                                    g
                                    h
                                    i
                                    j
                                    k
                                    l
                                    m
                                    n
                                    o
                                    p
                                    q
                                    r
                                    s
                                    t
                                    w
                                    v
                                    x
                                    y
                                    z";
        public string sufix = @"amentos
imentos
uciones
amento
imento
adoras
adores
logias
encias
amente
idades
ismos
istas
adora
acoes
antes
ancia
logia
ucion
encia
mente
idade
eiros
eiras
ezas
icos
icas
ismo
avel
ivel
ista
eiro
eira
osos
osas
ador
acao
ante
ivas
ivos
iras
eza
ico
ica
oso
osa
iva
ivo
ira
ariamos
eriamos
iriamos
assemos
essemos
issemos
arieis
erieis
irieis
asseis
esseis
isseis
aramos
eramos
iramos
avamos
aremos
eremos
iremos
ariam
eriam
iriam
assem
essem
issem
arias
erias
irias
ardes
erdes
irdes
asses
esses
isses
astes
estes
istes
areis
ereis
ireis
aveis
iamos
armos
ermos
irmos
aria
eria
iria
asse
esse
isse
aste
este
iste
arei
erei
irei
aram
eram
iram
avam
arem
erem
irem
ando
endo
indo
arao
erao
irao
adas
idas
aras
eras
iras
avas
ares
eres
ires
ieis
ados
idos
amos
emos
imos
iras
ada
ida
ara
era
ira
ava
iam
ado
ido
ias
ais
eis
ira
ia
ei
am
em
ar
er
ir
as
es
is
eu
iu
ou";
    }
}
